#! /bin/sh -

openssl req -x509 -nodes -newkey rsa:4096 -days 1825 -batch -out ./auditdistd.cert.pem -keyout ./auditdistd.key.pem

fingerprint="$(openssl x509 -in ./auditdistd.cert.pem -noout -fingerprint -sha256 | awk -F '[ =]' '{printf("%s=%s\n", $1, $3)}')"
password="$(dd if=/dev/urandom bs=32 count=1 | openssl base64 | cut -b -32)"

cat > auditdistd-receiver.conf << EOS
receiver {
	host "linux" {
		remote "tls://192.168.10.12"
		password "$password"
	}
}
EOS

cat > auditdistd-sender.conf << EOS
sender {
	host "freebsd" {
		remote "tls://192.168.10.11"
		fingerprint "$fingerprint"
		password "$password"
		directory "/var/log/audit/auditdistd"
	}
}
EOS
